### ISSUE TITLE
Plugin not working on Linux

### ISSUE THREAD

**Issue by Storungsucher** [BruteForceMaestro/SCPSense#1]
Plugin not working on Linux because Plugin create a .bin file in %appdata% which doesnt exist in Linux @BruteForceMaestro

**Comment by BruteForceMaestro** [comment]
did you test it yourself? if so, that's not an error, this plugin doesn't display your own stats
test it with another human

**Comment by BruteForceMaestro** [comment]
also, check out the new release. it should fix incorrect appdata formatting.

**Comment by Storungsucher** [comment]
I checked the latest Release you know that %appdata% doesn't exist on Linux Servers ? so its saving somewhere which doesn't exist and breaking the linux server. Also because of that the Server laggs and keeps spamming no such directory %appdata%

**Comment by BruteForceMaestro** [comment]
Path is now configurable. go check the newest release out
